// Main entry point for Azure Functions v4
// This file imports all functions to register them with the Azure Functions runtime

// Import all function modules
import "./functions/TestFunction";
import { AddUserGroup } from "./functions/TestFunction";
import "./functions/CheckUserRole";
import { CheckUserRole } from "./functions/CheckUserRole";
import "./functions/CreateGroup";
import { CreateGroup } from "./functions/CreateGroup";
import "./functions/GetGroups";
import { GetGroups } from "./functions/GetGroups";
import "./functions/CreateProduction";
import { CreateProduction } from "./functions/CreateProduction";
import "./functions/GetProductions";
import { GetProductions } from "./functions/GetProductions";
import "./functions/DeleteGroup";
import { DeleteGroup } from "./functions/DeleteGroup";
import "./functions/UpdateGroup";
import { UpdateGroup } from "./functions/UpdateGroup";
import "./functions/Dashboard";
import { Dashboard } from "./functions/Dashboard";
import "./functions/CreateUser";
import { CreateUser } from "./functions/CreateUser";
import "./functions/LoginUser";
import { LoginUser } from "./functions/LoginUser";
import "./functions/GetProductionById";
import { GetProductionById } from "./functions/GetProductionById";
import "./functions/UpdateProduction";
import { UpdateProduction } from "./functions/UpdateProduction";
import "./functions/DeleteProduction";
import { DeleteProduction } from "./functions/DeleteProduction";
import "./functions/ListUsers";
import { ListUsers } from "./functions/ListUsers";
import "./functions/GetUserById";
import { GetUserById } from "./functions/GetUserById";
import "./functions/UpdateUser";
import { UpdateUser } from "./functions/UpdateUser";
import "./functions/DeleteUser";
import { DeleteUser } from "./functions/DeleteUser";
import "./functions/GetMe";
import { GetMe } from "./functions/GetMe";
import "./functions/LogoutUser";
import { LogoutUser } from "./functions/LogoutUser";
import "./functions/RemoveUserFromGroup";
import { RemoveUserFromGroup } from "./functions/RemoveUserFromGroup";
import "./functions/GetUserGroups";
import { GetUserGroups } from "./functions/GetUserGroups";
import "./functions/GetGroup";
import { GetGroup } from "./functions/GetGroup";
import "./functions/ExportData";
import { ExportData } from "./functions/ExportData";
import "./functions/ImportData";
import { ImportData } from "./functions/ImportData";
import "./functions/GetUserByJWT";
import { GetUserByJWT } from "./functions/GetUserByJWT";
import "./functions/GetGroupsById";
import { GetGroupsById } from "./functions/GetGroupsById";
import "./functions/GetYearlyReport";
import { GetYearlyReport } from "./functions/GetYearlyReport";
import "./functions/GetCalcSettings";
import { GetCalcSettings } from "./functions/GetCalcSettings";
import "./functions/SaveCalcSettings";
import { SaveCalcSettings } from "./functions/SaveCalcSettings";
import "./functions/CalculateCarbonizationVolume";
import { CalculateCarbonizationVolume } from "./functions/CalculateCarbonizationVolume";
import "./functions/UploadPhoto";
import { UploadPhoto } from "./functions/UploadPhoto";
import "./functions/GetPhoto";
import { GetPhoto } from "./functions/GetPhoto";
import "./functions/UploadPdf";
import { UploadPdf } from "./functions/UploadPdf";
import "./functions/GetPdf";
import { GetPdf } from "./functions/GetPdf";
import "./functions/group-ranking";
import { GroupRanking } from "./functions/group-ranking";
import "./functions/group-rankings";
import { GroupRankings } from "./functions/group-rankings";
import "./functions/GetExtinguishingMethodRatio";
import { GetExtinguishingMethodRatio } from "./functions/GetExtinguishingMethodRatio";
import "./functions/CreateProductionSum";
import { CreateProductionSum } from "./functions/CreateProductionSum";
